local M = {}

local log = require("mani.core.log")
local sha = require("mani.lib.sha256")

function M.compute_hash(filepath)
  local f = io.open(filepath, "r")
  if not f then return "" end
  local content = f:read("*a")
  f:close()
  return sha.sha256(content)
end

function M.lua_version_str()
  return _VERSION:match("Lua (%d%.%d)") or "5.4"
end

function M.rocks_dir()
  return ".mani/tree/lib/luarocks/rocks-" .. M.lua_version_str()
end

function M.read_rockspec_source(name, version)
  local path = M.rocks_dir() .. "/" .. name .. "/" .. version .. "/" .. name .. "-" .. version .. ".rockspec"
  local f = io.open(path, "r")
  if not f then return "" end
  local content = f:read("*a")
  f:close()

  local env   = setmetatable({}, { __index = _G })
  local chunk = load(content, "=" .. path, "t", env)
  if not chunk then return "" end
  if not pcall(chunk) then return "" end

  local src = rawget(env, "source")
  if type(src) ~= "table" then return "" end
  return src.url or ""
end

function M.read_rockspec_deps(name, version)
  local path = M.rocks_dir() .. "/" .. name .. "/" .. version .. "/" .. name .. "-" .. version .. ".rockspec"
  local f = io.open(path, "r")
  if not f then return {} end
  local content = f:read("*a")
  f:close()

  local deps = {}
  local deps_block = content:match('dependencies%s*=%s*{(.-)}')
  if deps_block then
    for dep in deps_block:gmatch('"([^"]-)"') do
      local pkg_name = dep:match("^%s*([^%s>%<%=~]+)")
      if pkg_name and pkg_name ~= "lua" then
        table.insert(deps, pkg_name)
      end
    end
  end
  return deps
end

function M.compute_integrity(name, version)
  local rock_dir     = M.rocks_dir() .. "/" .. name .. "/" .. version
  local manifest_path = rock_dir .. "/rock_manifest"

  local f = io.open(manifest_path, "r")
  if not f then return "" end
  local mcontent = f:read("*a")
  f:close()

  local env   = setmetatable({}, { __index = _G })
  local chunk = load(mcontent, "=rock_manifest", "t", env)
  if not chunk then return "" end
  if not pcall(chunk) then return "" end

  local manifest = rawget(env, "rock_manifest")
  if type(manifest) ~= "table" then return "" end

  local lua_ver = M.lua_version_str()
  local tree = ".mani/tree"
  local hashes = {}

  local function category_base(cat)
    if cat == "lua" then return tree .. "/share/lua/" .. lua_ver
    elseif cat == "lib" then return tree .. "/lib/lua/" .. lua_ver
    elseif cat == "bin" then return tree .. "/bin"
    elseif cat == "doc" then return rock_dir .. "/doc"
    else return rock_dir .. "/" .. cat
    end
  end

  local function walk(base, tbl)
    for key, val in pairs(tbl) do
      if type(val) == "string" then
        local fh = io.open(base .. "/" .. key, "r")
        if fh then
          local data = fh:read("*a")
          fh:close()
          if data then table.insert(hashes, sha.sha256(data)) end
        end
      elseif type(val) == "table" then
        walk(base .. "/" .. key, val)
      end
    end
  end

  for cat, entries in pairs(manifest) do
    if type(entries) == "table" then
      walk(category_base(cat), entries)
    elseif type(entries) == "string" then
      local fh = io.open(rock_dir .. "/" .. cat, "r")
      if fh then
        local data = fh:read("*a")
        fh:close()
        if data then table.insert(hashes, sha.sha256(data)) end
      end
    end
  end

  if #hashes == 0 then return "" end
  table.sort(hashes)
  return sha.sha256(table.concat(hashes))
end

function M.read_full_lockfile()
  local result = {}
  local f = io.open("mani.lock.lua", "r")
  if not f then return result end
  f:close()

  local chunk = loadfile("mani.lock.lua")
  if not chunk then return result end
  local ok, res = pcall(chunk)
  if not ok or type(res) ~= "table" then return result end

  -- current format
  if res.packages and type(res.packages) == "table" then
    for name, info in pairs(res.packages) do
      if type(info) == "table" then result[name] = info end
    end
    return result
  end

  -- legacy format: { dependencies = { name = version } }
  if res.dependencies and type(res.dependencies) == "table" then
    for name, ver in pairs(res.dependencies) do
      result[name] = { version = ver, dependencies = {} }
    end
  end

  return result
end

function M.read_existing_lockfile_versions()
  local result = {}
  for name, info in pairs(M.read_full_lockfile()) do
    result[name] = info.version or ""
  end
  return result
end

function M.serialize_lockfile(manifest_hash, packages)
  local lines = {}
  local timestamp = os.date("!%Y-%m-%dT%H:%M:%SZ")

  table.insert(lines, "-- mani.lock.lua (auto-generated by mani, do not edit by hand!)")
  table.insert(lines, "-- generated: " .. timestamp)
  table.insert(lines, "return {")
  table.insert(lines, "  lockfile_version = \"1.0\",")
  table.insert(lines, "  manifest_hash = \"" .. manifest_hash .. "\",")
  table.insert(lines, "  packages = {")

  local names = {}
  for name in pairs(packages) do table.insert(names, name) end
  table.sort(names)

  for _, name in ipairs(names) do
    local pkg = packages[name]

    table.insert(lines, "    [\"" .. name .. "\"] = {")
    table.insert(lines, "      version = \"" .. (pkg.version or "") .. "\",")
    table.insert(lines, "      source = \"" .. (pkg.source or "") .. "\",")
    table.insert(lines, "      hash = \"" .. (pkg.hash or "") .. "\",")
    table.insert(lines, "      integrity = \"" .. (pkg.integrity or "") .. "\",")

    if pkg.dependencies and #pkg.dependencies > 0 then
      local parts = {}
      for _, dep in ipairs(pkg.dependencies) do
        table.insert(parts, "\"" .. dep .. "\"")
      end
      table.insert(lines, "      dependencies = { " .. table.concat(parts, ", ") .. " },")
    else
      table.insert(lines, "      dependencies = {},")
    end
    table.insert(lines, "    },")
  end

  table.insert(lines, "  }")
  table.insert(lines, "}")
  return table.concat(lines, "\n")
end

function M.verify_integrity(locked_tree)
  local all_ok = true
  for name, info in pairs(locked_tree) do
    local ver = info.version or ""
    local rockspec_path = M.rocks_dir() .. "/" .. name .. "/" .. ver .. "/" .. name .. "-" .. ver .. ".rockspec"

    if info.hash and info.hash ~= "" then
      local actual = M.compute_hash(rockspec_path)
      if actual ~= info.hash then
        log.error("rockspec hash mismatch for " .. name)
        all_ok = false
      end
    end

    if info.integrity and info.integrity ~= "" then
      local actual = M.compute_integrity(name, ver)
      if actual ~= info.integrity then
        log.error("file integrity mismatch for " .. name)
        all_ok = false
      end
    end
  end

  if all_ok then
    log.ok("all package integrity checks passed.")
  end
  return all_ok
end

function M.write_lockfile(manifest_hash, packages)
  local content = M.serialize_lockfile(manifest_hash, packages)
  local f = io.open("mani.lock.lua", "w")

  if not f then
    log.error("failed to open mani.lock.lua for writing")
    return false
  end

  f:write(content)
  f:close()
  log.ok("saved mani.lock.lua")
  return true
end

return M