local M = {}

local function trim(s)
  return (s:match("^%s*(.-)%s*$"))
end

local function lua_version_constraint(versions)
  local nums = {}
  local has_luajit = false

  for _, v in ipairs(versions) do
    if v == "luajit" then
      has_luajit = true
    else
      local n = tonumber(v)
      if n then table.insert(nums, n) end
    end
  end
  table.sort(nums)

  if #nums == 0 and has_luajit then
    return "lua >= 5.1"
  elseif #nums == 1 then
    return "lua ~> " .. nums[1]
  elseif #nums > 1 then
    local min = nums[1]
    local max = nums[#nums]
    return "lua >= " .. min .. ", < " .. (math.floor(max) + 1) .. ".0"
  end
  return "lua >= 5.4"
end

local function resolve_source_url(meta)
  if meta.source_url and meta.source_url ~= "" then
    return meta.source_url
  end

  if meta.homepage and meta.homepage:match("^https?://github%.com/") then
    return "git+" .. meta.homepage
  end

  local handle = io.popen("git config --get remote.origin.url 2>/dev/null")
  local remote_url = handle and handle:read("*l")
  if handle then handle:close() end

  if remote_url and remote_url ~= "" then
    if remote_url:match("^git@") then
      remote_url = remote_url:gsub("^git@([^:]+):", "https://%1/")
    end
    return "git+" .. remote_url:gsub("%.git$", "")
  end

  local log = require("mani.core.log")
  local fallback = "git+https://github.com/TODO_USER/" .. meta.name
  log.warn("no source_url or git remote found. using placeholder: " .. fallback)
  return fallback
end

local function build_modules(meta)
  -- walk src/ and register every .lua file as a module.
  -- falls back to a single entry if lfs is not available.
  local ok, lfs = pcall(require, "lfs")
  if not ok then
    return { ["  [\"" .. meta.name .. "\"] = \"src/main.lua\""] = true }
  end

  local modules = {}

  local function walk(dir, prefix)
    for entry in lfs.dir(dir) do
      if entry ~= "." and entry ~= ".." then
        local path = dir .. "/" .. entry
        local attr = lfs.attributes(path)
        if attr and attr.mode == "directory" then
          walk(path, prefix .. entry .. ".")
        elseif entry:match("%.lua$") then
          local mod_name = prefix .. entry:gsub("%.lua$", "")
          table.insert(modules, "    [\"" .. mod_name .. "\"] = \"" .. path .. "\",")
        end
      end
    end
  end

  walk("src", "")
  table.sort(modules)
  return modules
end

function M.generate(project)
  local log = require("mani.core.log")
  local meta = project.metadata
  if not meta then
    log.error("no project metadata found - call mani.project{} first")
    return false
  end

  -- dependencies
  local deps_lines = {}
  for _, dep in ipairs(project.dependencies or {}) do
    local pkg = trim(dep:gsub("^([^%^]+)%^(.+)$", "%1 >= %2"))
    table.insert(deps_lines, "  \"" .. pkg .. "\",")
  end

  -- bin
  local bin_lines = {}
  if meta.bin and next(meta.bin) then
    table.insert(bin_lines, "  install = {")
    table.insert(bin_lines, "    bin = {")
    for cmd_name, cmd_path in pairs(meta.bin) do
      table.insert(bin_lines, "      [\"" .. cmd_name .. "\"] = \"" .. cmd_path .. "\",")
    end
    table.insert(bin_lines, "    },")
    table.insert(bin_lines, "  },")
  end

  local source_url    = resolve_source_url(meta)
  local lua_dep       = lua_version_constraint(meta.lua_versions or {})
  local module_lines  = build_modules(meta)

  local lines = {
    "-- generated by mani - do not edit manually!",
    "-- use `mani add <pkg>` to add dependencies and `mani rockspec` to regenerate",
    "",
    "package = \"" .. meta.name .. "\"",
    "version = \"" .. meta.version .. "-1\"",
    "",
    "source = {",
    "  url = \"" .. source_url .. "\",",
    "  tag = \"v" .. meta.version .. "\",",
    "}",
    "",
    "description = {",
    "  summary  = \"" .. (meta.summary  or "") .. "\",",
    "  homepage = \"" .. (meta.homepage or "") .. "\",",
    "  license  = \"" .. (meta.license  or "") .. "\",",
    "}",
    "",
    "dependencies = {",
    "  \"" .. lua_dep .. "\",",
  }

  for _, l in ipairs(deps_lines) do table.insert(lines, l) end
  table.insert(lines, "}")
  table.insert(lines, "")
  table.insert(lines, "build = {")
  table.insert(lines, "  type = \"builtin\",")
  table.insert(lines, "  modules = {")
  for _, l in ipairs(module_lines) do table.insert(lines, l) end
  table.insert(lines, "  },")
  for _, l in ipairs(bin_lines) do table.insert(lines, l) end
  table.insert(lines, "}")
  table.insert(lines, "")

  local content  = table.concat(lines, "\n")
  local filename = meta.name .. "-" .. meta.version .. "-1.rockspec"

  os.execute("mkdir -p rockspecs")
  local f = io.open("rockspecs/" .. filename, "w")
  if not f then
    log.error("could not write rockspecs/" .. filename)
    return false
  end
  f:write(content)
  f:close()
  log.ok("wrote rockspecs/" .. filename)
  return true
end

return M
